spring:
  datasource:
    url: jdbc:mysql://localhost:3311/JXShop?useUnicode=true&characterEncoding=utf-8
    username: doudou
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8083